version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: diogenes
      POSTGRES_PASSWORD: diogenes
      POSTGRES_DB: diogenes
